image: natcap/userguide-build:0da3dbeaf1aa3a7bb4b7bd583db9fea708e61709
options:
    # Max time observed so far (as of 2019-04-09) has been < 6 minutes, so
    # 10 seems like a reasonable upper limit.
    max-time: 10
pipelines:
    # Build from the default branch
    branches:
        default:
            - step:
                name: Build and upload UG to GCP
                script:
                    # Build the User's Guide
                    - make html latex
                    - make -C build/latex all-pdf

                    # Authenticate as our service account and push artifacts to our releases storage bucket
                    - echo ${GOOGLE_SERVICE_ACC_KEY} > client-secret.json
                    - gcloud auth activate-service-account --key-file=client-secret.json
                    - gsutil -m rsync -dr build/html gs://releases.naturalcapitalproject.org/invest-userguide/latest
                    - gsutil cp build/latex/*.pdf gs://releases.naturalcapitalproject.org/invest-userguide/latest/

    # Build from commits from any branches other than default
    default:
        - step:
            name: Build UG only (no upload)
            script:
                # Build the User's Guide
                - make html latex
                - make -C build/latex all-pdf

            artifacts:
                - build/**
