image: natcap/userguide-build:0da3dbeaf1aa3a7bb4b7bd583db9fea708e61709
pipelines:
    default:
        - step:
            script:
                # Build the User's Guide
                - make html latex
                - make -C build/latex all-pdf

                # Authenticate as our service account and push artifacts to our releases storage bucket
                - echo ${GOOGLE_SERVICE_ACC_KEY} > client-secret.json
                - gcloud auth activate-service-account --key-file=client-secret.json
                - gsutil -m rsync -dr build/html gs://releases.naturalcapitalproject.org/invest-userguide/latest
                - gsutil cp build/latex/*.pdf gs://releases.naturalcapitalproject.org/invest-userguide/latest/
