name: User's Guide
on:
    push:  # Build the docs for any branch (we only push to GCP when building from master)
        branches:
            - '*'

    create:  # Any time a tag is added, rebuild the docs.
        branches:
            - master

    pull_request:  # Build the docs for any PR
        branches:
            - '*'
jobs:
    build-ug:
        name: Sphinx docs
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1

            - name: Set up python
              uses: actions/setup-python@v1
              with:
                  python-version: 3.7

            - name: Install python dependencies
              run: python -m pip install -r requirements.txt

            - name: Build sphinx docs
              run: |
                  make html

            - name: Set up GCP SDK
              if: ${{ github.ref == 'refs/heads/master' }}
              uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
              with:
                  version: '281.0.0'
                  service_account_key: ${{ secrets.GCP_SERVICE_ACC_KEY }}

            - name: Upload to GCS
              if: ${{ github.ref == 'refs/heads/master' }}
              run: |
                gsutil -m rsync -dr build/html gs://releases.naturalcapitalproject.org/invest-userguide/latest

            - name: Save UG artifacts
              uses: actions/upload-artifact@v1
              with:
                  name: InVEST User's Guide
                  path: build/html
