name: User's Guide
on: [push, pull_request]
jobs:
    build-ug:
        name: Sphinx docs
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1

            - name: Set up python
              uses: actions/setup-python@v1
              with:
                  python-version: 3.7

            - name: Install python dependencies
              run: python -m pip install sphinx setuptools_scm

            - name: Download pandoc
              run: |
                  wget https://github.com/jgm/pandoc/releases/download/2.9.2/pandoc-2.9.2-linux-amd64.tar.gz
                  tar -xvzf pandoc-2.9.2-linux-amd64.tar.gz

            - name: Build sphinx docs
              run: |
                  make PANDOC=./pandoc-2.9.2/bin/pandoc html

            - name: Set up GCP SDK
              if: ${{ github.head_ref == 'master' }}
              uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
              with:
                  version: '281.0.0'
                  service_account_key: ${{ secrets.GCP_SERVICE_ACC_KEY }}

            - name: Upload to GCS
              if: ${{ github.head_ref == 'master' }}
              run: |
                gsutil -m rsync -dr build/html gs://releases.naturalcapitalproject.org/invest-userguide/latest

            - name: Save UG artifacts
              uses: actions/upload-artifact@v1
              with:
                  name: InVEST User's Guide
                  path: build/html
