name: Match tags from InVEST
on:
    push:  # Also check for tags when pushed.
        branches: master
    schedule:
        # Also check for tags daily.
        cron: '0 0 * * *'

jobs:
    check-invest-tags:
        name: Compare tags with InVEST
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - run: git fetch --prune --unshallow

            - name: Check out InVEST
              uses: actions/checkout@v2
              with:
                  repository: natcap/invest
                  path: invest-src

            - name: Fetch tags for InVEST
              run: git -C invest-src fetch origin +refs/tags/*:refs/tags/*

            - name: Add any needed tags to the UG
              run: ./.github/workflows/match-invest-tags.yml

            - name: Push new tags back to UG
              run: git push --tags https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPO.git
